- name: Create Parameters
  hosts: localhost
  connection: local
  tasks:
    - name: Create Parameters
      community.aws.aws_ssm_parameter_store:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        region: us-east-1
      loop:
        - {name: "dev.cart1.REDIS_HOST", value: "redis-dev.awsctr.online" }
        - {name: "dev.cart1.CATALOGUE_HOST", value: "catalogue-dev.awsctr.online" }
        - {name: "dev.catalogue.MONGO", value: "true" }
       # - {name: "dev.catalogue.MONGO_URL", value: "mongodb://mongodb-dev.awsctr.online:27017/catalogue" }
        - {name: "dev.catalogue.MONGO_URL", value: "mongodb://mongodb-dev.awsctr.online:27017/catalogue" }
        - {name: "dev.frontend.CATALOGUE_URL", value: "http://catalogue-dev.awsctr.online:80/" }
        - {name: "dev.frontend.CART1_URL", value: "http://cart1-dev.awsctr.online:80/" }
        - {name: "dev.frontend.USER_URL", value: "http://user-dev.awsctr.online:80/" }
        - {name: "dev.frontend.PAYMENT_URL", value: "http://payment-dev.awsctr.online:80/" }
        - {name: "dev.frontend.SHIPPING_URL", value: "http://shipping-dev.awsctr.online:80/" }
        - {name: "dev.payment.CART1_HOST", value: "cart1-dev.awsctr.online" }
        - {name: "dev.payment.USER_HOST", value: "user-dev.awsctr.online" }
        - {name: "dev.payment.CART1_PORT", value: "80" }
        - {name: "dev.payment.USER_PORT", value: "80" }
        - {name: "dev.payment.AMQP_HOST", value: "rabbitmq-dev.awsctr.online" }
        - {name: "dev.dispatch.AMQP_HOST", value: "rabbitmq-dev.awsctr.online" }
        - {name: "dev.payment.AMQP_USER", value: "roboshop" }
        - {name: "dev.shipping.CART1_ENDPOINT", value: "cart1-dev.awsctr.online:80" }
        - {name: "dev.shipping.DB_HOST", value: "mysql-dev.awsctr.online" }
        - {name: "dev.user.MONGO", value: "true" }
        - {name: "dev.user.MONGO_URL", value: "mongodb://mongodb-dev.awsctr.online:27017/users" }
        - {name: "dev.user.REDIS_HOST", value: "redis-dev.awsctr.online" }

    ### PASSWORDS SHOULD NEVER BE KEPT IN THESE REPOS, THOSE SHOULD BE CREATED MAUALLY, BUT FOR LAB PURPOSE IAM CREATING HERE
    - name: Create Secrets
      community.aws.aws_ssm_parameter_store:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        region: us-east-1
        string_type: "SecureString"
      loop:
        - {name: "dev.payment.AMQP_PASS", value: "roboshop1234" }
        - { name: "dev.rabbitmq.AMQP_USER", value: "roboshop" }
        - {name: "dev.rabbitmq.AMQP_PASS", value: "roboshop1234" }
        - {name: "dev.mysql.DB_ADMIN_USER", value: "root" }
        - {name: "dev.mysql.DB_ADMIN_PASS", value: "RoboShop@1" }
        - {name: "dev.docdb.DB_ADMIN_USER", value: "admin1" }
        - {name: "dev.docdb.DB_ADMIN_PASS", value: "RoboShop123" }
        - {name: "dev.rds.DB_ADMIN_USER", value: "admin1" }
        - {name: "dev.rds.DB_ADMIN_PASS", value: "RoboShop123" }
        - { name: "dev.rabbitmq.USER", value: "roboshop" }
        - { name: "dev.rabbitmq.PASS", value: "roboshop1234" }
        - { name: "dev.dispatch.AMQP_PASS", value: "roboshop1234" }
        - { name: "dev.dispatch.AMQP_USER", value: "roboshop" }
        - { name: "grafana.api_key", value: "eyJrIjoiSEpHZUl6dGY0Ym51WkNDNGlJVmM1MUdlbzQ4akpWa2MiLCJuIjoiY2xpIiwiaWQiOjF9" }
        - { name: "ses.USER", value: "AKIA2ZVKWW2HJR3MMLZQ" }
        - { name: "ses.PASS", value: "BOJ6ePXcMzce7Mtqz0u/u4o3GAy2OJOqb4jL0TOtB+Oy" }
        - { name: "dev.ssh.USER", value: "centos" }
        - { name: "dev.ssh.PASS", value: "DevOps321" }



