{
 "title": "{{component}}",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "componentprocess",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"{{env}}-{{component}}\",exported_name=\"{{component}}.service\",state=\"active\"}"
    }
   ]
  },
  {
   "title": "cputimeseries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (name) (floor(rate(node_cpu_seconds_total{ mode=\"idle\", name=\"{{env}}-{{component}}\"}[1m]) * 100)))"
    }
   ]
  },
  {
   "title": "memoryused_percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_memory_used_percent{name=\"{{env}}-{{component}}\"}"
    }
   ]
  },
  {
   "title": "cpu%",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (name) (floor(rate(node_cpu_seconds_total{ mode=\"idle\", name=\"{{env}}-{{component}}\"}[1m]) * 100)))"
    }
   ]
  }
 ]
}