- name: setup elastic file repo
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: install filebeat
  ansible.builtin.yum:
    name: filebeat
    state: installed

# filebeat configuration is in the path cd /etc/filebeat/filebeat.yml
- name: copy filebeat configuration
  ansible.builtin.template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- name : start filebeat
  ansible.builtin.systemd:
    name: filebeeat
    state: restarted
