- name: Update Logstash conf
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name : restart logstashconf
  ansible.builtin.systemd:
    name: logstash
    state: restarted
