- name: sethostname
  ansible.builtin.shell: set-hostname {{component}}

- name: Install prometheus Node Exporter
  ansible.builtin.shell: labauto prometheus-node-exporter

- name: setup prometheus Alerts configuration
  ansible.builtin.template:
    src: alert.yml
    dest: /tmp/alert.yml

# this is used to copy the file from shippinng, mpayment, user or dispatch alerts-rules.yml to prometheus alerts alerts-rules.yml with componenet name here we are using if server are password based we use this type of connection
- name: copy the prometheus Alert configuration to Prometheus server
  ansible.builtin.shell: sshpass -p {{ lookup('aws_ssm', '{{env}}.ssh.PASS', region='us-east-1' ) }}  scp /tmp/alert.yml {{ lookup('aws_ssm', '{{env}}.ssh.USER', region='us-east-1' ) }}@172.31.0.96:/opt/prometheus/alerts/{{component}}.yml


# this code is in elk folder this will import the code from elk folder

- name: Import elk
  ansible.builtin.import_role:
    name: elk

# creating grafana dashboard using json code
- name: make template
  ansible.builtin.template:
    src: grafana-template.json
    dest: /tmp/grafana.json
    remote_src: yes

- name: Import Grafana dashboard
  community.grafana.grafana_dashboard:
    grafana_url: http://172.31.0.96:3000
    grafana_api_key: "{{ lookup('aws_ssm', 'grafana.api_key', region='us-east-1' ) }}"
    state: present
    overwrite: yes
    path: /tmp/grafana.json